common: &common
  adapter: postgresql
  encoding: utf8
  pool: 50

development:
  <<: *common
  database: cencolproject
  username: AdamChow
  password: dckyn25ac92IOS

production:
  <<: *common
  database: cencolproject
  host: 192.168.1.101
  username: pi
  password: raspberry
  
#production:
#  <<: *common
#  database: cencolproject
#  username: AdamChow
#  password: dckyn25ac92IOS